<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 31" tests="1" total_time="Finished in: 2.76 secs."/>
<test location="D:\Project\GitHub\recommendation_system\SSF\movie-recommendation\src\backend\PyUnitTest\mainTest.py" status="error" test="Test.test_readUrm" time="">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "D:\Project\GitHub\recommendation_system\SSF\movie-recommendation\src\backend\PyUnitTest\mainTest.py", line 23, in test_readUrm
    urm[int(row[0]), int(row[1])] = float(row[2])
ValueError: could not convert string to float: 'rating'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Project\GitHub\recommendation_system\SSF\movie-recommendation\src\backend\PyUnitTest\mainTest.py", line 25, in test_readUrm
    urm[row[0], row[1], row[2]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
]]></stderr>
</test>
<launch mode="debug">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="movie-recommendation mainTest.py (2)"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
