<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="1" failures="0" finished="true" name="Test Run: 59" tests="1" total_time="Finished in: 0.00 secs."/>
<test location="D:\Project\GitHub\recommendation_system\SSF\movie-recommendation\src\backend\PyUnitTest\mainTest.py" status="error" test="Test.test_readUrm" time="">
<stdout/>
<stderr><![CDATA[Traceback (most recent call last):
  File "D:\Project\GitHub\recommendation_system\SSF\movie-recommendation\src\backend\PyUnitTest\mainTest.py", line 18, in test_readUrm
    urm = np.zeros(shape=(MAX_UID,MAX_PID), dtype=np.float32)
MemoryError
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="movie-recommendation mainTest.py (2)"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
